spring:
  admin-datasource:
    url: jdbc:tc:mariadb:latest:///admin"
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password:
  site-datasource:
    url: jdbc:tc:mariadb:latest:///site"
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password:
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  flyway:
    locations: classpath:db/migration/admin
